ALTER TABLE public."running_record"
  ALTER COLUMN record_id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public."running_record"
  ADD COLUMN IF NOT EXISTS path jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS elapsed_seconds integer DEFAULT 0;

DROP POLICY IF EXISTS "running_record_select" ON public."running_record";
DROP POLICY IF EXISTS "running_record_insert" ON public."running_record";

CREATE POLICY "running_record_select"
  ON public."running_record"
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public."user" u
      WHERE u.user_id = running_record.user_id
        AND u.auth_user_id = auth.uid()
    )
  );

CREATE POLICY "running_record_insert"
  ON public."running_record"
  FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public."user" u
      WHERE u.user_id = running_record.user_id
        AND u.auth_user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "user_select_self" ON public."user";
CREATE POLICY "user_select_self"
  ON public."user"
  FOR SELECT
  TO authenticated
  USING (auth.uid() = auth_user_id);
